language: java
sudo: enabled
dist: trusty

before_install:
  # helpful when debugging directory layout problems
  - sudo apt-get install -y tree

install:
  - ./gradlew setup --no-daemon --stacktrace -Pon-travis=true

script:
  - ./gradlew buildAll --no-daemon --stacktrace

deploy:
  provider: script
  script: ./gradlew pushSite --no-daemon --stacktrace -Pon-travis=true
  skip_cleanup: true
  on:
    branch: grandmaster
